import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Car } from "lucide-react";
import { CartContext, CartProvider } from "./[slug]/menu/contexts/cart";

const poopins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "FSW Donalds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poopins.className} antialiased`}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
